spring:
  datasource:
    url: jdbc:mysql://tinyurl.fofcn.com:3306/tiny_urldb?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: tinyurl_user
    password: Yy123456.
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
